#!/usr/bin/env bash
# Run on the Raspberry Pi as the kiosk user (same account as labwc, usually admin).
#
# Priority:
#   1) pactl (PipeWire-Pulse + pulseaudio-utils): pick non-HDMI USB sink, set default, PULSE_SINK.
#   2) wpctl only (PipeWire without pactl): set default USB sink id, PULSE_SINK from wpctl inspect.
#   3) ALSA-only: ~/.asoundrc + Extension Unit + ALSA_CARD in s52-carplay-audio.env.
#
# From your Mac (do NOT run this script locally on macOS — no amixer/pi ALSA stack):
#   S52_HOST=192.168.1.96 ./scripts/ssh-pi.sh 'bash -s' < scripts/pi-audio-usb-default.sh
set -euo pipefail

if [[ "$(uname -s)" != Linux ]]; then
  echo "This script must run on the Pi (Linux), not on $(uname -s)." >&2
  echo "From your Mac:  S52_HOST=192.168.x.x ./scripts/ssh-pi.sh 'bash -s' < scripts/pi-audio-usb-default.sh" >&2
  exit 1
fi

USB_CARD="${S52_USB_ALSA_CARD:-${ALSA_CARD:-Audio}}"

usb_extension_unmute() {
  if ! command -v amixer &>/dev/null; then
    return 0
  fi
  if ! amixer -c "${USB_CARD}" info &>/dev/null; then
    return 0
  fi
  amixer -c "${USB_CARD}" sset PCM 100% >/dev/null 2>&1 || true
  amixer -c "${USB_CARD}" sset 'Extension Unit' on >/dev/null 2>&1 || true
}

write_env_pulse() {
  local sink_name="$1"
  mkdir -p "${HOME}/.config"
  {
    echo "# Generated by pi-audio-usb-default.sh — $(date -Iseconds)"
    printf 'export PULSE_SINK=%q\n' "${sink_name}"
    echo "export ALSA_CARD=${USB_CARD}"
  } >"${HOME}/.config/s52-carplay-audio.env"
  chmod 600 "${HOME}/.config/s52-carplay-audio.env"
  echo "Wrote ${HOME}/.config/s52-carplay-audio.env"
  echo "Restart kiosk: sudo systemctl restart s52-cage-kiosk"
}

alsa_usb_fix() {
  echo "=== ALSA-only path — card ${USB_CARD} ==="
  if ! command -v amixer &>/dev/null; then
    echo "amixer missing; install: sudo apt-get install -y alsa-utils" >&2
    return 1
  fi
  if ! amixer -c "${USB_CARD}" info &>/dev/null; then
    echo "No ALSA card '${USB_CARD}'. aplay -l:" >&2
    aplay -l >&2 || true
    return 1
  fi
  usb_extension_unmute
  mkdir -p "${HOME}/.config"
  cat >"${HOME}/.asoundrc" <<EOF
# S52: default playback to USB DAC (see aplay -l).
pcm.!default {
    type plug
    slave.pcm "hw:${USB_CARD},0"
}
ctl.!default {
    type hw
    card ${USB_CARD}
}
EOF
  chmod 644 "${HOME}/.asoundrc"
  {
    echo "# Generated by pi-audio-usb-default.sh — $(date -Iseconds)"
    echo "export ALSA_CARD=${USB_CARD}"
  } >"${HOME}/.config/s52-carplay-audio.env"
  chmod 600 "${HOME}/.config/s52-carplay-audio.env"
  echo "Wrote ~/.asoundrc and ~/.config/s52-carplay-audio.env"
  echo "Optional once: sudo alsactl store"
  echo "Restart kiosk: sudo systemctl restart s52-cage-kiosk"
}

wpctl_usb_sink_id() {
  # Match sink line only (not "Devices" 48. USB Audio): must include "Analog".
  wpctl status 2>/dev/null | grep 'USB Audio Analog' | head -1 | grep -oE '[0-9]+' | head -1
}

wpctl_pipewire_usb_fix() {
  echo "=== PipeWire (wpctl) — USB sink ==="
  local sid name
  sid="$(wpctl_usb_sink_id)"
  if [[ -z "${sid}" ]]; then
    echo "Could not find USB Audio sink in: wpctl status" >&2
    wpctl status >&2 || true
    return 1
  fi
  wpctl set-default "${sid}" 2>/dev/null || true
  wpctl set-volume "${sid}" 100% unmute 2>/dev/null || true
  name="$(wpctl inspect "${sid}" 2>/dev/null | sed -n 's/^  \* node.name = "\(.*\)"/\1/p' | head -1)"
  if [[ -z "${name}" ]]; then
    echo "wpctl inspect ${sid} did not yield node.name" >&2
    return 1
  fi
  echo "Default sink id=${sid}  PULSE_SINK=${name}"
  usb_extension_unmute
  write_env_pulse "${name}"
  if command -v pactl &>/dev/null; then
    pactl set-default "${name}" 2>/dev/null || true
    echo "Current default (pactl): $(pactl get-default-sink 2>/dev/null || echo n/a)"
  fi
}

if command -v pactl &>/dev/null; then
  pick_sink() {
    local line
    while read -r line; do
      case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
        *hdmi* | *vc4hdmi*) continue ;;
      esac
      case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
        *usb* | *dac* | *cmedia* | *c-media* | *fosi* | *sabrent* | *ugreen* | *generic_usb*)
          echo "$line" | awk '{print $2}'
          return 0
          ;;
      esac
    done < <(pactl list sinks short)

    while read -r line; do
      case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
        *hdmi* | *vc4hdmi*) continue ;;
      esac
      echo "$line" | awk '{print $2}'
      return 0
    done < <(pactl list sinks short)

    return 1
  }

  SINK_NAME="$(pick_sink || true)"
  if [[ -z "${SINK_NAME:-}" ]]; then
    echo "No Pulse sink matched; trying wpctl USB sink…" >&2
    wpctl_pipewire_usb_fix || alsa_usb_fix
    exit 0
  fi

  echo "Using Pulse default sink: ${SINK_NAME}"
  pactl set-default "${SINK_NAME}"
  if command -v wpctl &>/dev/null; then
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 100% unmute 2>/dev/null || true
  fi
  usb_extension_unmute
  write_env_pulse "${SINK_NAME}"
  echo "Current default sink: $(pactl get-default-sink)"
  exit 0
fi

if command -v wpctl &>/dev/null && wpctl status 2>/dev/null | grep -q 'USB Audio'; then
  wpctl_pipewire_usb_fix
  exit 0
fi

alsa_usb_fix
