#!/usr/bin/env bash
# Run on the Raspberry Pi as the kiosk user (same account as labwc, usually admin).
# Picks a non-HDMI audio sink (prefers USB/DAC in the sink name), sets it as the
# PulseAudio-on-PipeWire default, writes ~/.config/s52-carplay-audio.env, and
# reminds you to restart the kiosk so react-carplay picks up PULSE_SINK.
#
# From your Mac (same LAN as the Pi):
#   S52_HOST=192.168.x.x ./scripts/ssh-pi.sh 'bash -s' < scripts/pi-audio-usb-default.sh
set -euo pipefail

if ! command -v pactl &>/dev/null; then
  echo "pactl not found. On Pi OS Lite try: sudo apt-get install -y pipewire-pulse" >&2
  exit 1
fi

pick_sink() {
  # Column 2 is the sink name in "pactl list sinks short"
  local line
  while read -r line; do
    case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
      *hdmi* | *vc4hdmi*) continue ;;
    esac
    case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
      *usb* | *dac* | *cmedia* | *c-media* | *fosi* | *sabrent* | *ugreen*)
        echo "$line" | awk '{print $2}'
        return 0
        ;;
    esac
  done < <(pactl list sinks short)

  while read -r line; do
    case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
      *hdmi* | *vc4hdmi*) continue ;;
    esac
    echo "$line" | awk '{print $2}'
    return 0
  done < <(pactl list sinks short)

  return 1
}

SINK_NAME="$(pick_sink || true)"
if [[ -z "${SINK_NAME:-}" ]]; then
  echo "No usable sink found. Output of: pactl list sinks short" >&2
  pactl list sinks short >&2 || true
  exit 1
fi

echo "Using sink: ${SINK_NAME}"
pactl set-default "${SINK_NAME}"

if command -v wpctl &>/dev/null; then
  wpctl set-volume @DEFAULT_AUDIO_SINK@ 100% unmute 2>/dev/null || true
fi

mkdir -p "${HOME}/.config"
{
  echo "# Generated by pi-audio-usb-default.sh — $(date -Iseconds)"
  printf 'export PULSE_SINK=%q\n' "${SINK_NAME}"
} >"${HOME}/.config/s52-carplay-audio.env"
chmod 600 "${HOME}/.config/s52-carplay-audio.env"

echo "Wrote ${HOME}/.config/s52-carplay-audio.env"
echo "Restart kiosk: sudo systemctl restart s52-cage-kiosk"
echo "Current default sink: $(pactl get-default-sink)"
