#!/usr/bin/env bash
# Run on the Raspberry Pi as the kiosk user (same account as labwc, usually admin).
#
# - If pactl exists (PipeWire/Pulse): pick a non-HDMI sink, set default, write PULSE_SINK.
# - Else (ALSA-only Lite): unmute USB "Extension Unit", write ~/.asoundrc + s52-carplay-audio.env.
#
# From your Mac (same LAN as the Pi):
#   S52_HOST=192.168.x.x ./scripts/ssh-pi.sh 'bash -s' < scripts/pi-audio-usb-default.sh
set -euo pipefail

USB_CARD="${S52_USB_ALSA_CARD:-${ALSA_CARD:-Audio}}"

alsa_usb_fix() {
  echo "=== ALSA-only path (no pactl) — card ${USB_CARD} ==="
  if ! command -v amixer &>/dev/null; then
    echo "amixer missing; install alsa-utils" >&2
    return 1
  fi
  if ! amixer -c "${USB_CARD}" info &>/dev/null; then
    echo "No ALSA card '${USB_CARD}'. aplay -l:" >&2
    aplay -l >&2 || true
    return 1
  fi
  amixer -c "${USB_CARD}" sset PCM 100% || true
  amixer -c "${USB_CARD}" sset 'Extension Unit' on || true
  mkdir -p "${HOME}/.config"
  cat >"${HOME}/.asoundrc" <<EOF
# S52: default playback to USB DAC (see aplay -l).
pcm.!default {
    type plug
    slave.pcm "hw:${USB_CARD},0"
}
ctl.!default {
    type hw
    card ${USB_CARD}
}
EOF
  chmod 644 "${HOME}/.asoundrc"
  {
    echo "# Generated by pi-audio-usb-default.sh — $(date -Iseconds)"
    echo "export ALSA_CARD=${USB_CARD}"
  } >"${HOME}/.config/s52-carplay-audio.env"
  chmod 600 "${HOME}/.config/s52-carplay-audio.env"
  echo "Wrote ~/.asoundrc and ~/.config/s52-carplay-audio.env"
  echo "Optional once (saves mixer state across reboot): sudo alsactl store"
  echo "Restart kiosk: sudo systemctl restart s52-cage-kiosk"
}

if command -v pactl &>/dev/null; then
  pick_sink() {
    local line
    while read -r line; do
      case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
        *hdmi* | *vc4hdmi*) continue ;;
      esac
      case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
        *usb* | *dac* | *cmedia* | *c-media* | *fosi* | *sabrent* | *ugreen*)
          echo "$line" | awk '{print $2}'
          return 0
          ;;
      esac
    done < <(pactl list sinks short)

    while read -r line; do
      case $(echo "$line" | tr '[:upper:]' '[:lower:]') in
        *hdmi* | *vc4hdmi*) continue ;;
      esac
      echo "$line" | awk '{print $2}'
      return 0
    done < <(pactl list sinks short)

    return 1
  }

  SINK_NAME="$(pick_sink || true)"
  if [[ -z "${SINK_NAME:-}" ]]; then
    echo "No Pulse sink matched; falling back to ALSA USB fix." >&2
    alsa_usb_fix
    exit 0
  fi

  echo "Using Pulse default sink: ${SINK_NAME}"
  pactl set-default "${SINK_NAME}"

  if command -v wpctl &>/dev/null; then
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 100% unmute 2>/dev/null || true
  fi

  mkdir -p "${HOME}/.config"
  {
    echo "# Generated by pi-audio-usb-default.sh — $(date -Iseconds)"
    printf 'export PULSE_SINK=%q\n' "${SINK_NAME}"
  } >"${HOME}/.config/s52-carplay-audio.env"
  chmod 600 "${HOME}/.config/s52-carplay-audio.env"

  echo "Wrote ${HOME}/.config/s52-carplay-audio.env"
  echo "Restart kiosk: sudo systemctl restart s52-cage-kiosk"
  echo "Current default sink: $(pactl get-default-sink)"
  exit 0
fi

alsa_usb_fix
